language: cpp

before_script:
  - git clone --depth 1 https://github.com/duongdoOrg/Trilinos Trilinos
  - chmod +x Trilinos/do-configure
  - mkdir BUILD
  - cd BUILD
  
script:
  - ../Trilinos/./do-configure -DTrilinos_ENABLE_TeuchosCore=ON
